name: Build and push image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('shadow-cljs.edn') }}
      - run: yarn
      - run: yarn build
      - run: docker build -t ghcr.io/valerauko/personal-advent:${{ github.sha }} .
      - run: docker push ghcr.io/valerauko/personal-advent:${{ github.sha }}
